//! Pure logic for the `zpp init` subcommand. Scaffolds a fresh Zig++ project
//! tree at a user-supplied directory. Writes four files:
//!
//!   - main.zpp          : a minimal trait/struct example
//!   - build.zig         : a Zig 0.16-style module build script
//!   - build.zig.zon     : the manifest, with a stable per-name fingerprint
//!   - .gitignore        : ignores zig-out/, .zig-cache/, .zpp-out/, .zpp-doc/
//!
//! No I/O outside the target directory; the CLI driver in tools/zpp.zig is
//! responsible for arg parsing, error reporting, and the next-steps message.

const std = @import("std");

// ---------------------------------------------------------------------------
// Templates
//
// Each template uses a single placeholder string `<PROJECT_NAME>` (or
// `<PROJECT_NAME_SAFE>` / `<FNV_HASH>` for the manifest) which `scaffold`
// replaces at write time. Keeping them as `pub const`s lets tests look at the
// raw template if we need to.
// ---------------------------------------------------------------------------

pub const main_zpp_template: []const u8 =
    \\//! Generated by `zpp init`. Edit this file to start your Zig++ project.
    \\
    \\const std = @import("std");
    \\
    \\trait Greeter {
    \\    fn greet(self) void;
    \\}
    \\
    \\const Hello = struct {
    \\    name: []const u8,
    \\
    \\    pub fn greet(self: *Hello) void {
    \\        std.debug.print("hello, {s}!\n", .{self.name});
    \\    }
    \\};
    \\
    \\pub fn main() void {
    \\    var hello = Hello{ .name = "<PROJECT_NAME>" };
    \\    const g: Greeter = Greeter.from(&hello);
    \\    g.greet();
    \\}
    \\
;

pub const build_zig_template: []const u8 =
    \\const std = @import("std");
    \\
    \\// TODO: edit this path to point at your checkout's lib/zpp.zig.
    \\// Required so derive(.{...}) lowering output (which references zpp.derive.*)
    \\// can resolve. If your project doesn't use derive, you can leave this and
    \\// the addImport call alone — unused module imports are harmless.
    \\const lib_zpp_path = "../zigpp/lib/zpp.zig";
    \\
    \\pub fn build(b: *std.Build) void {
    \\    const target = b.standardTargetOptions(.{});
    \\    const optimize = b.standardOptimizeOption(.{});
    \\
    \\    const zpp_mod = b.createModule(.{
    \\        .root_source_file = b.path(lib_zpp_path),
    \\        .target = target,
    \\        .optimize = optimize,
    \\    });
    \\
    \\    const exe_module = b.createModule(.{
    \\        .root_source_file = b.path(".zpp-out/main.zig"),
    \\        .target = target,
    \\        .optimize = optimize,
    \\    });
    \\    exe_module.addImport("zpp", zpp_mod);
    \\
    \\    const exe = b.addExecutable(.{
    \\        .name = "<PROJECT_NAME>",
    \\        .root_module = exe_module,
    \\    });
    \\    b.installArtifact(exe);
    \\
    \\    const run_cmd = b.addRunArtifact(exe);
    \\    run_cmd.step.dependOn(b.getInstallStep());
    \\    if (b.args) |args| run_cmd.addArgs(args);
    \\    const run_step = b.step("run", "Run the application");
    \\    run_step.dependOn(&run_cmd.step);
    \\}
    \\
;

pub const build_zon_template: []const u8 =
    \\.{
    \\    .name = .<PROJECT_NAME_SAFE>,
    \\    .version = "0.0.0",
    \\    .fingerprint = 0x<FNV_HASH>,
    \\    .minimum_zig_version = "0.15.0",
    \\    .dependencies = .{},
    \\    .paths = .{ "build.zig", "build.zig.zon", ".zpp-out" },
    \\}
    \\
;

pub const gitignore_template: []const u8 =
    \\zig-out/
    \\.zig-cache/
    \\.zpp-out/
    \\.zpp-doc/
    \\.DS_Store
    \\
;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

pub const ScaffoldError = error{
    DirNotEmpty,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Scaffold a new Zig++ project at `dir_path`. Behavior:
///   - If the dir doesn't exist, create it.
///   - If the dir exists and is empty, proceed.
///   - If the dir exists and is non-empty, return ScaffoldError.DirNotEmpty
///     unless `force` is set.
///
/// `project_name` is the human-facing name (used in main.zpp greeting and as
/// the build artifact name). It does NOT have to be a valid Zig identifier —
/// the function sanitizes it for the .zon `.name` field internally.
///
/// On success, four files are written. On --force, only the four template
/// files are overwritten; any other contents of the directory are left alone.
pub fn scaffold(
    allocator: std.mem.Allocator,
    dir_path: []const u8,
    project_name: []const u8,
    force: bool,
) !void {
    // Step 1: ensure the destination directory exists; reject non-empty
    // unless --force.
    try ensureTargetDir(dir_path, force);

    var dir = try std.fs.cwd().openDir(dir_path, .{});
    defer dir.close();

    // Step 2: derive the safe identifier and the fingerprint.
    const safe_name = try sanitizeProjectName(allocator, project_name);
    defer allocator.free(safe_name);

    const fingerprint = computeFingerprint(project_name);

    // Step 3: render and write each file.
    const main_zpp = try renderTemplate(
        allocator,
        main_zpp_template,
        .{ .project_name = project_name },
    );
    defer allocator.free(main_zpp);
    try dir.writeFile(.{ .sub_path = "main.zpp", .data = main_zpp });

    const build_zig = try renderTemplate(
        allocator,
        build_zig_template,
        .{ .project_name = project_name },
    );
    defer allocator.free(build_zig);
    try dir.writeFile(.{ .sub_path = "build.zig", .data = build_zig });

    const build_zon = try renderZon(
        allocator,
        safe_name,
        fingerprint,
    );
    defer allocator.free(build_zon);
    try dir.writeFile(.{ .sub_path = "build.zig.zon", .data = build_zon });

    try dir.writeFile(.{ .sub_path = ".gitignore", .data = gitignore_template });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Check the destination state and reject non-empty dirs unless `force`.
/// Creates the directory (and any missing parents) if it doesn't exist.
fn ensureTargetDir(dir_path: []const u8, force: bool) !void {
    const stat = std.fs.cwd().statFile(dir_path) catch |err| switch (err) {
        error.FileNotFound => {
            try std.fs.cwd().makePath(dir_path);
            return;
        },
        else => return err,
    };
    if (stat.kind != .directory) return error.NotDir;

    if (force) return;

    var d = try std.fs.cwd().openDir(dir_path, .{ .iterate = true });
    defer d.close();
    var it = d.iterate();
    if (try it.next()) |_| {
        return ScaffoldError.DirNotEmpty;
    }
}

/// Replace every occurrence of `<PROJECT_NAME>` in `template` with the supplied
/// project name. Caller owns the returned slice.
fn renderTemplate(
    allocator: std.mem.Allocator,
    template: []const u8,
    ctx: struct { project_name: []const u8 },
) ![]u8 {
    return replaceAll(allocator, template, "<PROJECT_NAME>", ctx.project_name);
}

/// Render the build.zig.zon manifest, swapping in the safe identifier and the
/// 16-hex-digit fingerprint.
fn renderZon(
    allocator: std.mem.Allocator,
    safe_name: []const u8,
    fingerprint: u64,
) ![]u8 {
    var hex_buf: [16]u8 = undefined;
    const hex = std.fmt.bufPrint(
        &hex_buf,
        "{x:0>16}",
        .{fingerprint},
    ) catch unreachable;

    const after_name = try replaceAll(
        allocator,
        build_zon_template,
        "<PROJECT_NAME_SAFE>",
        safe_name,
    );
    defer allocator.free(after_name);

    return replaceAll(allocator, after_name, "<FNV_HASH>", hex);
}

/// Allocator-backed replace-all. Returns a freshly allocated slice; caller
/// frees with the same allocator. No special handling of overlapping needles.
fn replaceAll(
    allocator: std.mem.Allocator,
    haystack: []const u8,
    needle: []const u8,
    replacement: []const u8,
) ![]u8 {
    var out = std.ArrayList(u8){};
    errdefer out.deinit(allocator);

    var i: usize = 0;
    while (i < haystack.len) {
        if (i + needle.len <= haystack.len and
            std.mem.eql(u8, haystack[i .. i + needle.len], needle))
        {
            try out.appendSlice(allocator, replacement);
            i += needle.len;
        } else {
            try out.append(allocator, haystack[i]);
            i += 1;
        }
    }

    return out.toOwnedSlice(allocator);
}

/// Project-name sanitization: `[a-zA-Z0-9_]` survive as-is; everything else
/// (including `-`) becomes `_`. If the result starts with a digit, prefix `_`
/// so it's a valid Zig identifier (a Zig package name is a `.name = .ident`
/// enum literal — `0my_app` doesn't lex). An empty input becomes `world`.
fn sanitizeProjectName(allocator: std.mem.Allocator, name: []const u8) ![]u8 {
    if (name.len == 0) return allocator.dupe(u8, "world");

    var out = std.ArrayList(u8){};
    errdefer out.deinit(allocator);

    if (std.ascii.isDigit(name[0])) {
        try out.append(allocator, '_');
    }

    for (name) |c| {
        if (std.ascii.isAlphanumeric(c) or c == '_') {
            try out.append(allocator, c);
        } else {
            try out.append(allocator, '_');
        }
    }

    if (out.items.len == 0) {
        try out.appendSlice(allocator, "world");
    }

    return out.toOwnedSlice(allocator);
}

/// FNV-1a 64-bit hash over the project name. Stable, project-specific, and
/// good enough for a placeholder fingerprint — Zig will tell the user the
/// canonical value if it cares.
fn computeFingerprint(name: []const u8) u64 {
    const fnv_offset: u64 = 0xcbf29ce484222325;
    const fnv_prime: u64 = 0x100000001b3;
    var h: u64 = fnv_offset;
    for (name) |c| {
        h ^= @as(u64, c);
        h = h *% fnv_prime;
    }
    return h;
}

/// Best-effort identifier check: derives the basename from a path, used by
/// the CLI driver when the user's project name needs to be inferred.
pub fn projectNameFromPath(dir_path: []const u8) []const u8 {
    const base = std.fs.path.basename(dir_path);
    if (base.len == 0) return "world";
    // basename of "." or "./" can come back as "." — fall back so the
    // generated greeter doesn't read "hello, .!".
    if (std.mem.eql(u8, base, ".")) return "world";
    return base;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

fn tmpAbsPath(allocator: std.mem.Allocator, tmp: *std.testing.TmpDir) ![]u8 {
    var buf: [std.fs.max_path_bytes]u8 = undefined;
    const real = try tmp.dir.realpath(".", &buf);
    return allocator.dupe(u8, real);
}

test "scaffold: fresh dir creates exactly 4 non-empty files with substituted name" {
    var tmp = std.testing.tmpDir(.{ .iterate = true });
    defer tmp.cleanup();

    const allocator = testing.allocator;

    const tmp_path = try tmpAbsPath(allocator, &tmp);
    defer allocator.free(tmp_path);

    const proj_path = try std.fs.path.join(allocator, &.{ tmp_path, "demo" });
    defer allocator.free(proj_path);

    try scaffold(allocator, proj_path, "demo", false);

    // Open from the tmp side for inspection.
    var proj = try tmp.dir.openDir("demo", .{ .iterate = true });
    defer proj.close();

    var count: usize = 0;
    var seen_main = false;
    var seen_build = false;
    var seen_zon = false;
    var seen_gitignore = false;
    var it = proj.iterate();
    while (try it.next()) |entry| {
        count += 1;
        if (std.mem.eql(u8, entry.name, "main.zpp")) seen_main = true;
        if (std.mem.eql(u8, entry.name, "build.zig")) seen_build = true;
        if (std.mem.eql(u8, entry.name, "build.zig.zon")) seen_zon = true;
        if (std.mem.eql(u8, entry.name, ".gitignore")) seen_gitignore = true;
    }
    try testing.expectEqual(@as(usize, 4), count);
    try testing.expect(seen_main);
    try testing.expect(seen_build);
    try testing.expect(seen_zon);
    try testing.expect(seen_gitignore);

    const main_src = try proj.readFileAlloc(allocator, "main.zpp", 1 << 20);
    defer allocator.free(main_src);
    try testing.expect(main_src.len > 0);
    // The substituted greeting line must show the project name.
    try testing.expect(std.mem.indexOf(u8, main_src, "Hello{ .name = \"demo\" }") != null);

    const build_src = try proj.readFileAlloc(allocator, "build.zig", 1 << 20);
    defer allocator.free(build_src);
    try testing.expect(build_src.len > 0);

    const zon_src = try proj.readFileAlloc(allocator, "build.zig.zon", 1 << 20);
    defer allocator.free(zon_src);
    try testing.expect(zon_src.len > 0);

    const gi_src = try proj.readFileAlloc(allocator, ".gitignore", 1 << 20);
    defer allocator.free(gi_src);
    try testing.expect(gi_src.len > 0);
}

test "scaffold: non-empty dir without force returns DirNotEmpty" {
    var tmp = std.testing.tmpDir(.{ .iterate = true });
    defer tmp.cleanup();

    try tmp.dir.makePath("proj");
    try tmp.dir.writeFile(.{ .sub_path = "proj/squatter.txt", .data = "x\n" });

    const allocator = testing.allocator;

    const tmp_path = try tmpAbsPath(allocator, &tmp);
    defer allocator.free(tmp_path);

    const proj_path = try std.fs.path.join(allocator, &.{ tmp_path, "proj" });
    defer allocator.free(proj_path);

    const result = scaffold(allocator, proj_path, "proj", false);
    try testing.expectError(ScaffoldError.DirNotEmpty, result);
}

test "scaffold: --force overwrites template files in non-empty dir" {
    var tmp = std.testing.tmpDir(.{ .iterate = true });
    defer tmp.cleanup();

    try tmp.dir.makePath("proj");
    // Pre-existing junk that --force must NOT delete.
    try tmp.dir.writeFile(.{ .sub_path = "proj/squatter.txt", .data = "x\n" });
    // Pre-existing main.zpp with stale content.
    try tmp.dir.writeFile(.{ .sub_path = "proj/main.zpp", .data = "// stale\n" });

    const allocator = testing.allocator;

    const tmp_path = try tmpAbsPath(allocator, &tmp);
    defer allocator.free(tmp_path);

    const proj_path = try std.fs.path.join(allocator, &.{ tmp_path, "proj" });
    defer allocator.free(proj_path);

    try scaffold(allocator, proj_path, "proj", true);

    var proj = try tmp.dir.openDir("proj", .{ .iterate = true });
    defer proj.close();

    // Stale junk preserved.
    const sq = try proj.readFileAlloc(allocator, "squatter.txt", 1 << 20);
    defer allocator.free(sq);
    try testing.expectEqualStrings("x\n", sq);

    // Template overwrite happened.
    const main_src = try proj.readFileAlloc(allocator, "main.zpp", 1 << 20);
    defer allocator.free(main_src);
    try testing.expect(std.mem.indexOf(u8, main_src, "Hello{ .name = \"proj\" }") != null);
    try testing.expect(std.mem.indexOf(u8, main_src, "// stale") == null);
}

test "scaffold: name with dash sanitizes for zon but stays raw in build.zig" {
    var tmp = std.testing.tmpDir(.{ .iterate = true });
    defer tmp.cleanup();

    const allocator = testing.allocator;

    const tmp_path = try tmpAbsPath(allocator, &tmp);
    defer allocator.free(tmp_path);

    const proj_path = try std.fs.path.join(allocator, &.{ tmp_path, "my-app" });
    defer allocator.free(proj_path);

    try scaffold(allocator, proj_path, "my-app", false);

    var proj = try tmp.dir.openDir("my-app", .{ .iterate = true });
    defer proj.close();

    const zon_src = try proj.readFileAlloc(allocator, "build.zig.zon", 1 << 20);
    defer allocator.free(zon_src);
    try testing.expect(std.mem.indexOf(u8, zon_src, ".name = .my_app,") != null);

    const build_src = try proj.readFileAlloc(allocator, "build.zig", 1 << 20);
    defer allocator.free(build_src);
    // The Zig string literal in addExecutable's .name = "..." can hold a dash.
    try testing.expect(std.mem.indexOf(u8, build_src, "\"my-app\"") != null);
}

test "computeFingerprint: stable across repeated calls" {
    const a = computeFingerprint("demo");
    const b = computeFingerprint("demo");
    try testing.expectEqual(a, b);

    // Different names should (almost certainly) hash differently.
    const c = computeFingerprint("other");
    try testing.expect(a != c);
}

test "sanitizeProjectName: leading digit gets underscore prefix; non-ident chars become underscore" {
    const allocator = testing.allocator;

    const a = try sanitizeProjectName(allocator, "9lives");
    defer allocator.free(a);
    try testing.expectEqualStrings("_9lives", a);

    const b = try sanitizeProjectName(allocator, "my.cool-pkg");
    defer allocator.free(b);
    try testing.expectEqualStrings("my_cool_pkg", b);

    const c = try sanitizeProjectName(allocator, "");
    defer allocator.free(c);
    try testing.expectEqualStrings("world", c);
}
